### ISSUE TITLE
Add Google Analytics tracking

### ISSUE THREAD

**Issue by mpoehler** [mpoehler/firebase-amp-pwa#22]
With use of the Google Tag Manager and the offline capabilities of workbox.

**Comment by mpoehler** [comment]
In Google Tag Manager we need two different Containers. One normal Web and one AMP. But they share the analytics setting I guess. Maybe there is a way to make that somehow nice?

- [ ] Create an Analytics Account
- [ ] Create a GTM Account for Testing purposes
- [ ] Create an AMP Container in GTM
- [ ] Configure AMP Container to use Analytics Account for Pageviews
- [ ] Create a WEB Container in GTM
- [ ] Add vue-gtm (https://github.com/mib200/vue-gtm) to the project
- [ ] Configure WEB Container to use Analytics Account for Pageviews
- [ ] enable Workbox analytics
- [ ]  test and confirm. That offline works

**Comment by mpoehler** [comment]
https://builtvisible.com/google-analytics-for-pwas-tracking-offline-behaviour-and-more/

**Comment by mpoehler** [comment]
We should start to think about the .env - we need to integrate the TrackingId during the AMP-Page generation process as well as in the VueJs app. In the VueJs app we should utilize the embedded .env support. 

I would suggest to have the following environments:

- **production** - the final production env
- **staging** - a production version, but not the final url
- **dev** - for use during development
- **test** - for use with testing

When it comes to Google Analytics, 
- **production** - contains the final GA-Tracking Id, with the custom dimension set to "production"
- **staging** - contains the final GA-Tracking Id, with the custom dimension set to "staging"
- **dev** - contains the final GA-Tracking Id, with the custom dimension set to "dev"
- **test** - contains the final GA-Tracking Id, with the custom dimension set to "test"

It is also important, that .env can be overwritten by variables set in the environment. This is important, because all settings in the CI-Build will be set with environment variables.

**Comment by mpoehler** [comment]
So next steps:

check if we can add a trackingId and custom dimension in all environment incl. overwritten by env variables.
